# Generated by Django 4.2.3 on 2023-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
