# Generated by Django 4.2.3 on 2023-07-26 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
