# Generated by Django 4.2.3 on 2023-11-15 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_candidate_databases_candidate_frameworks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='age',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
    ]
