# Generated by Django 4.2.3 on 2023-11-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_candidate_about_course_candidate_about_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume', verbose_name='Resume'),
        ),
    ]
